/* eslint-disable import/prefer-default-export */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_DEVICE_TIMEZONE = 'SET_DEVICE_TIMEZONE';

export const SET_DEVICE_LOCALE = 'SET_DEVICE_LOCALE';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_LIST_BOOKING_LOCATION = 'SET_LIST_BOOKING_LOCATION';

export const SET_LIST_BANK = 'SET_LIST_BANK';

export const RESET_STORE_SIGN_OUT = 'RESET_STORE_SIGN_OUT';

export const SET_LIST_NOTIFICATION = 'SET_LIST_NOTIFICATION';

export const SET_CHATTING_WITH = 'SET_CHATTING_WITH';

export const SET_DATA_LISTENED = 'SET_DATA_LISTENED';

export const SET_MESSAGE_LISTENED = 'SET_MESSAGE_LISTENED';

export const SET_LIST_CONVERSATION = 'SET_LIST_CONVERSATION';

export const SET_NUMBER_MESSAGE_UNREAD = 'SET_NUMBER_MESSAGE_UNREAD';

export const SET_EXPO_TOKEN = 'SET_EXPO_TOKEN';

export const SET_NUMBER_NOTIFICATION_UNREAD = 'SET_NUMBER_NOTIFICATION_UNREAD';

export const SET_NAVIGATION = 'SET_NAVIGATION';

export const SET_PERSON_TAB_ACTIVE_INDEX = 'SET_PERSON_TAB_ACTIVE_INDEX';

export const SET_LIST_CASH_HISTORY_STORE = 'SET_LIST_CASH_HISTORY_STORE';

export const SET_LIST_BOOKING_STORE = 'SET_LIST_BOOKING_STORE';

export const SET_VERIFICATION_STORE = 'SET_VERIFICATION_STORE';

export const SET_IS_SIGN_IN_OTHER_DEVICE_STORE = 'SET_IS_SIGN_IN_OTHER_DEVICE_STORE';

export const SET_SHOW_LOADER_STORE = 'SET_SHOW_LOADER_STORE';

export const SET_NOTIFICATION_RECEIVED_REDUX = 'SET_NOTIFICATION_RECEIVED_REDUX';

export const SET_CURRENT_BOOKING_REDUX = 'SET_CURRENT_BOOKING_REDUX';

export const SET_LIST_PARTNER_HOME_REDUX = 'SET_LIST_PARTNER_HOME_REDUX';

export const SET_COUNTDOWN_SEND_OTP_REDUX = 'SET_COUNTDOWN_SEND_OTP_REDUX';
